name: Lint source code

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  UV_SYSTEM_PYTHON: "1"  # make uv do global installs

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install Ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: --version
        version: 0.9.2

    - name: Lint with Ruff
      run: ruff check --output-format=github

    - name: Format with Ruff
      run: ruff format --diff
